### ISSUE TITLE
Where to place cheats?

### ISSUE THREAD

**Issue by RevanXVIV** [Arch9SK7/BDSP#1]
I'm trying to get the cheats for brillaint diamond to work but the instructions say put on root of SD not in content folder for Brilliant diamond will either or work?

EDIT: I tried the file you put on GBAtemp and while the cheat codes did show up in edizon, it crashes my brilliant diamond every time.

**Comment by Arch9SK7** [comment]
> I'm trying to get the cheats for brillaint diamond to work but the instructions say put on root of SD not in content folder for Brilliant diamond will either or work?
> 
> EDIT: I tried the file you put on GBAtemp and while the cheat codes did show up in edizon, it crashes my brilliant diamond every time.

You need to make sure you edit your config file and move it in atmosphere so it doesnt try loading all cheats at once. The gbatemp thread has instructions to do that. 

Download either BD or SP depending pn what version you plan to use. Extract the folder.
Enter inside BD/SP then enter into which ever version you plan to use. Inside is an atmosphere folder. Just drag that to your root to get the cheats placed correctly.

https://pastebin.com/hJaJpeuD directions for the config file also here.
